spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false
    username: root
    password: root4977
    driver-class-name: com.mysql.cj.jdbc.Driver
  # name of the application displayed in the Eureka dashboard
  boot:
    message: Hello world from the auth

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      # properties:
      #   hibernate:
      #     dialect: org.hibernate.dialect.MySQLDialect

  

server:
  port: 8084

# # Eureka server configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  jwt:
    secret: MySecretKey1234567890!@#      # You should use a stronger key in prod
    expiration: 3600000    
