spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?useSSL=false
    username: root
    password: root4977
    driver-class-name: com.mysql.cj.jdbc.Driver
  # name of the application displayed in the Eureka dashboard
  boot:
    message: Hello world from the employee

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      # properties:
      #   hibernate:
      #     dialect: org.hibernate.dialect.MySQLDialect

  

server:
  port: 8081

# # Eureka server configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
