spring:
  datasource:
     url: jdbc:mysql://localhost:3306/organization_db?useSSL=false
     username: root
     password: root4977
     driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    message: Welcome to Organization Service  


management:
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
     # properties:
     #   hibernate:
     #     dialect: org.hibernate.dialect.MySQLDialect
 # Eureka server configuration
eureka:
   client:
     service-url:
       defaultZone: http://localhost:8761/eureka

#  All the other configs are commented as now they are referred from properties file from github except for the application name
